### ISSUE TITLE
Would love the ability to press enter on the open tab screen to start the focus or break session

### ISSUE THREAD

**Issue by alexkolson** [schmich/marinara#123]
Instead of having to click the button on the screen every time.

**Comment by schmich** [comment]
Awesome idea. I'm getting ready to release a new version in the next few days (with all of the translations), so I'll sneak this in with everything.

**Comment by alexkolson** [comment]
Hooray!

**Comment by alexkolson** [comment]
Wow! Already committed!! Thanks for taking your free time to make a nagging mouse-averse user of your free product extra happy!

**Comment by alexkolson** [comment]
@schmich Just wanted to say I got this update today and it's so nice! Pretty cool how such a small feature can add so much awesome! Thanks again!
