### ISSUE TITLE
Losing the pomo in middle of session

### ISSUE THREAD

**Issue by k-csh** [schmich/marinara#144]
Hi there -
I am not sure what I am doing to cause this, but every so often I lose the running pomo. I read that changing options and saving could cause this - still true? What about closing the browser window if another browser window is still open? I have also noticed that sometimes the pomo minutes do not change  - seem to be stuck on same number even though I know many minutes have passed.  This could be where I was working in another application for a while but browser window open. In terms of recommended usage - is it preferable to keep a browser window open with JUST marinara running to prevent the issues described here?

**Comment by schmich** [comment]
Thanks for the details. I definitely want to figure out what's going on here.

Yes, changing any options will reset the Pomodoro. It sucks and I can fix that behavior, I just haven't had a lot of feedback about it being a problem.

For recommended usage, as long as *any* Chrome browser window is open, Marinara should work just fine. It doesn't need a dedicated browser window, it just needs Chrome to be running.

As for the minutes not changing:

- The timer display should update every minute. It is *possible* that Chrome notices you aren't using the browser and decides to skip the update to save on power, but this would be the first I've heard of that happening
- When you notice the Pomodoro minutes frozen, if you wait for a few minutes, do they "catch up" or change at all, or are they permanently frozen? If you wait the remainder of the Pomodoro time, does the timer still expire (end of session)?
- Are you on a desktop or laptop? If laptop, do you ever sleep/close the lid? There's a similar issue (#68) related to sleep

Thanks again for the detailed report.

**Comment by schmich** [comment]
I dug a bit deeper into the Chrome extension documentation. There are better (more reliable) facilities for doing timers than what I'm currently using.

I would still appreciate if you could provide more details around your issues (take your time), but I will also investigate using the native Chrome alarms for implementing timers.

**Comment by schmich** [comment]
I've published Version 13 to the store. The extension now uses Chrome's built-in timer facility. I also fixed a potential bug where the timer display didn't update frequently enough.

I'm closing this issue for now. If you still see this behavior with Version 13, please comment and leave additional details and I will look into it further.
