### ISSUE TITLE
I can't save my setting for the volume

### ISSUE THREAD

**Issue by panluobu** [schmich/marinara#153]

**Comment by schmich** [comment]
Hi! There are currently no volume settings, so I assume you are asking for volume conrols? Which sounds are you wanting to change the volume for?

**Comment by benlind** [comment]
Whatever the intention of the OP, I would like a way to adjust the volume of all the sound effects (especially the "when complete" sounds).

**Comment by schmich** [comment]
Closing this in favor of #151. I've received a lot of feedback on this and will be adding volume controls for everything.
