### ISSUE TITLE
Mala traducción en Español 

### ISSUE THREAD

**Issue by fcojavierjorge** [schmich/marinara#160]
Saludos, en el mensaje que aparece en la barra de notificaciones tras cumplir un tiempo aparece la palabra "Concetrarse" como se puede ver en la siguiente imagen:

![image](https://user-images.githubusercontent.com/34709138/34201625-63a36004-e575-11e7-88ea-cb8303fa3ad6.png)

La palabra correcta sería "CONCENTRARTE".

¿Alguien lo puede arreglar?

Gracias

**Comment by schmich** [comment]
Hola. Yo no hablo español Esto está traducido.

Actualizaré el mensaje para decir "Comienza a Concentrarte".

¡Gracias por los comentarios!

**Comment by schmich** [comment]
Acabo de publicar la Versión 15 con la solución. Gracias de nuevo.
