### ISSUE TITLE
Mixed future and past on daily distribution

### ISSUE THREAD

**Issue by tretkow** [schmich/marinara#162]
It's Thursday 10 am, but on the daily distribution chart I see bars from yesterday night. See the picture: 
![marinara](https://user-images.githubusercontent.com/128558/34556221-c60e11fa-f135-11e7-8011-53deb24e50a8.png); Had this issue earlier, reinstalled but it didn't solve the issue.

Maybe it is somehow related to my timezone (UTC+1)?
My setup: Ubuntu 17.10. Chrome: 63.0.3239.84

**Comment by schmich** [comment]
The wording is misleading. 

Both charts are aggregations of all of your activity ever. The top chart breaks down your Pomodoros into hours of the day. The bottom chart breaks down your Pomodoros into days of the week. The idea is to show you your general activity levels bucketed by hours/days.

More stats are coming with #75 including current day/week stats, which it sounds like you were expecting here.

**Comment by schmich** [comment]
Closing since this will be addressed in #75.
