### ISSUE TITLE
Show Pomodoro Timeline for the day

### ISSUE THREAD

**Issue by dday4thedeceiver** [schmich/marinara#166]
Would be great if history tab included a history of the day.

1-Columns: Start Time, End Time, Type (Long break/Short Break/Focus)
2-Running total of Break Time and Focus Time

**Comment by schmich** [comment]
Unfortunately, this extension only tracks the Pomodoros you complete, not the breaks. This is still good feedback, though. I've incorporated it into #75, which is what I'm using to track feedback on more advanced statistics.

I'm closing this issue in favor of #75. Thanks again for the feedback.
