### ISSUE TITLE
Day should reset each calendar day

### ISSUE THREAD

**Issue by XGenius** [schmich/marinara#174]
I'm not sure what is considered a "day" at this point, but it doesn't make sense. I will often see multiple days worth of Pomodoro's listed. Then seemingly randomly, it resets at some point.

It would be great if it reset each day at midnight, or 3am if some people are working late, or maybe user defined. But it should reset every 24 hours.

**Comment by schmich** [comment]
There are two types of daily stats:

1. The "Completed Today" and "Today" stats, which reset every 24 hours:

![image](https://user-images.githubusercontent.com/1562839/36701629-00ca9dde-1b09-11e8-885a-341bc566d257.png)

![image](https://user-images.githubusercontent.com/1562839/36701605-e4bc60e6-1b08-11e8-9287-eae21b5fbf2c.png)

2. The "Daily Distribution" chart which shows an aggregated, bucketed view of your daily activity across all time. This never resets and will always grow as you complete more Pomodoros. It should probably be called "All-time Daily Distribution":

![image](https://user-images.githubusercontent.com/1562839/36701826-9989e2e6-1b09-11e8-9c51-840a9091881b.png)

Are your referring to 1 when talking about the random resets and multiple days worth of Pomodoros listed?

For 1, the daily stats are computed relative to midnight local time. Local time is determined by your browser/OS, so whatever your system clock says is what Marinara should be using to determine day boundaries.

It's possible there is a bug, but this is the first I've heard of any issues. If you want to export and share your history, I can poke at it a bit to see if I can reproduce what you're seeing.

**Comment by schmich** [comment]
Closing. If you have more details or questions, feel free to reopen this issue.
