### ISSUE TITLE
Option to hide units and or use larger fonts

### ISSUE THREAD

**Issue by 0e318236-1680-41a8-a989-3c9227637cdf** [schmich/marinara#186]
I don't believe this shows seconds. And the font in the icon is pretty small. 

Would be nice to be able to make them larger.

**Comment by schmich** [comment]
I assume you're talking about the browser action icon:

![image](https://user-images.githubusercontent.com/1562839/39545292-93bfbfdc-4e05-11e8-877a-4892c0583934.png)

Unfortunately, I do not control the font size. It is determined entirely by Chrome itself, and they give no options for modifying it.
