### ISSUE TITLE
[Feature Request] Block site when running pomodoro?

### ISSUE THREAD

**Issue by kuqadk3** [schmich/marinara#189]
Hi,

Thanks for such a nice and useful plugin.
I have a real pleasure to use it.

Hope you guys will add black-list site block so that user can import their list of sites they want to block when on pomodoro like :facebook,youtube,etc...

**Comment by abrarShariar** [comment]
This could be useful but not generic enough I guess

**Comment by tutitran** [comment]
i actually think it's incredibly useful. the whole point of having a pomodoro is to block out distractions. if a user sees a reminder that these websites are blocked, they would go back to their websites.

**Comment by schmich** [comment]
Thanks for the feedback. This is a much requested feature and will probably happen at some point after some features and bug fixes. For now, I am closing this as a duplicate of #32 (I've added your feedback there).
