### ISSUE TITLE
Suggestion: Please consider adding a soft applause to end of focus task

### ISSUE THREAD

**Issue by J3ySD** [schmich/marinara#215]
I think this would be really nice perhaps on a psychological level too to hear an applause after finishing a pomodoro. I would like to hear what everyone else thinks.

**Comment by schmich** [comment]
Sure! I've been using [freesound](https://freesound.org/browse/) as the source for sounds. If you can find a good sound there, I can add it.

The license on the sound should be permissive. See [here](https://github.com/schmich/marinara/blob/master/src/ATTRIBUTION) for the licenses currently in use.

**Comment by J3ySD** [comment]
Thanks for such a quick response. I will go ahead and look for that at
freesounds! Keep up the good work!
