### ISSUE TITLE
Desktop notifications are no longer popping up...

### ISSUE THREAD

**Issue by fudginghell** [schmich/marinara#221]
Hi, my desktop marinara notifications have stopped popping up... just the web notification in google chrome.  I have removed and reinstalled the extension but still no joy.

**Comment by schmich** [comment]
The published extension has been unchanged for a while, so this sudden change is strange. It's working fine on my laptop.

Just to be sure, is the "Show desktop notification" option enabled?

![screen shot 2018-11-02 at 9 43 56 am](https://user-images.githubusercontent.com/1562839/47928530-dc208180-de83-11e8-9c93-73db71913924.png)

Also, have you installed any other extensions recently? It's possible that some other extension interferes with Marinara's behavior.

If all the settings look correct, I'll need more info to figure out what's going on:

Steps:

1. Open Chrome's extensions page (chrome://extensions)

![image](https://user-images.githubusercontent.com/1562839/47928749-518c5200-de84-11e8-978a-c5f8ef03c96c.png)

2. Enable Developer mode in the top right corner

![image](https://user-images.githubusercontent.com/1562839/47928789-708ae400-de84-11e8-949f-251f436a2ecc.png)

3. Click the background page link in the Marinara extension box

![image](https://user-images.githubusercontent.com/1562839/47928791-7680c500-de84-11e8-80ce-db113b020bcb.png)

4. Go to the Console tab in the DevTools window that pops up

![image](https://user-images.githubusercontent.com/1562839/47928806-7ed90000-de84-11e8-8d5e-d1607ca379af.png)

5. Keep the DevTools window open and run through your scenario: start and complete a Pomodoro. You can set a shorter timer to get through it quickly.

6. Go back to the DevTools window and copy/paste and send any errors or messages that show up under the Console tab.

**Comment by fudginghell** [comment]
Hi Chris,

I removed any extensions that I had installed after installing Marinara
which had no effect and then I ran the scenario, no errors showed up under
the console tab... I found the desktop notifications far more useful than
the web page one..

Thanks,

Lisa Jones
SVN
m: 07938192986
e: lisa.jones1501@gmail.com
[image: google plus icon] <https://plus.google.com/u/0/>

**Comment by schmich** [comment]
I'm closing this issue as there hasn't been any activity for a while. If this is still a problem, let me know.
