### ISSUE TITLE
Daylight savings time is not taken into account

### ISSUE THREAD

**Issue by Zander46** [schmich/marinara#222]
Looking at the Daily Distribution graph in History, it doesn't appear that Daylight savings time is being accounted for, because the times stated in the graph are 1 hour later than they should be.

**Comment by schmich** [comment]
This is related to issue #182. The data is stored correctly but displayed incorrectly. Unfortunately, I haven't had time to dig in and fix this issue yet.

**Comment by schmich** [comment]
Closing as a duplicate of #182. Thanks for reporting this. I am starting to fix smaller bugs here and there, so I should be able to get to this.
