### ISSUE TITLE
Determine current browser support

### ISSUE THREAD

**Issue by schmich** [schmich/marinara#226]
- Add to GH pages feature list
- Add to extension description in CWS
- Chrome
- Opera
- Vivaldi
- Brave
- Firefox
- Others?
- File bugs?

### Opera

Opera has its [own store](https://addons.opera.com/en/extensions) and can also install Chrome extensions through Opera's "Install Chrome Extensions" extension.

![image](https://user-images.githubusercontent.com/1562839/49109189-f5c4a700-f23e-11e8-95ec-6dbc02be7e14.png)

**Comment by dbautistav** [comment]
See #192.

**Comment by schmich** [comment]
Thanks. Closing this meta issue in favor of using GitHub's projects to track this set of issues. [See here](https://github.com/schmich/marinara/projects/1) for the project.
