### ISSUE TITLE
add On/Off short break.

### ISSUE THREAD

**Issue by Hosify** [schmich/marinara#253]
Sometimes I just need a timer to remind me every half hour without any break.

**Comment by schmich** [comment]
I don't completely understand. Can you describe what you mean in more detail? Can you give me an example?

Are you saying that you just want to set a timer/alarm to go off every 30 minutes without anything Pomodoro related?

**Comment by Hosify** [comment]
Yes, Normally i use Marinara as Pomodoro. 
Sometimes, I use it as a timer/alarm to remind me to do something periodically, but without showing Short Break and Long Break.
So, Maybe you just need to add a function, turn on/turn off Short Break, It have had the function to turn off Long Break.
Hope you understand my poor English.

![image](https://user-images.githubusercontent.com/29913859/50976962-309f4780-152c-11e9-8a8f-0e8fdc5d69d3.png)
