### ISSUE TITLE
Completed today circles not appearing

### ISSUE THREAD

**Issue by Mithunbalraj** [schmich/marinara#257]
I came here to make a request to be able to track when Pomodoros are completed in a day (I have been using Marinara for many many months). But I looked through previous issues and found that there are already 'completed today' circles that are supposed to be displaying. 

This is how the history page looks for me: 
<img width="578" alt="screenshot 2019-01-29 at 1 59 13 pm" src="https://user-images.githubusercontent.com/14543243/51894650-62d6f300-23ce-11e9-8ef9-f2d8a17d6501.png">

I've never seen these circles. I use Chrome across both my Windows 10 desktop and Mac.

Please let me know if there's something I should do from my end to fix this, or whether it's a bug? And if so, what additional information I can give you to make your lives easier! 

EDIT: I just realized this might have been about the _number_ of Pomodoros completed in a day - what I had intended to ask about was to get the information of _when_ they were completed. If that's not a feature yet, it would lovely if it could be added! 

Thanks

**Comment by schmich** [comment]
Your understanding is correct. There is no display for _when_ Pomodoros are completed in a day, just the count. The "circles" are specifically referring to the expiration page visualization:

![image](https://user-images.githubusercontent.com/1562839/51936125-56499f00-23bc-11e9-8af3-f849effe26a8.png)

There are a lot of ideas for stats improvement (see #75), and showing details of what was completed today is definitely on that list.

If you could do me a favor, can you create a new issue explaining the feature you want in detail? That way, I can add it to the [stats update project](https://github.com/schmich/marinara/projects/2) and break off a bit of #75 which has gotten too big to be useful.

I'll close this issue. Thanks for the feedback!
