### ISSUE TITLE
New tab notification isn't working

### ISSUE THREAD

**Issue by phillipsemilyann** [schmich/marinara#259]
Hi, 

I'm very new to GitHub, so I apologize if I'm not submitting this correctly. 

I have been using Marinara for a week or so and love it, but as of this morning, my new tab notifications no longer pop up. The sound still plays, though. I just can't get notifications. I double checked my settings and the "show new tab notification" and "show desktop notification" boxes are all still checked. Now that I think about it, I don't think I've ever gotten a desktop notification... 

Thank you for your help in advance!

**Comment by phillipsemilyann** [comment]
Hi! Apologies for the delay in responding to you. I followed your instructions above and it doesn't seem that any errors occurred. I'm sorry I can't be more helpful! This seems to only happen intermittently... I will try opening a new window and see how that works, then report back.

**Comment by schmich** [comment]
I have a potential fix for this that will be in the next release which I should be able to publish within the next week.

**Comment by phillipsemilyann** [comment]
Awesome! Thanks for taking the time to look into this. Have a great day!

**Comment by schmich** [comment]
I realize this is much later than intended, but this _should_ be fixed in the latest release, version 27. I'm closing this issue for now. If this is still a problem, feel free to reactivate it and I can investigate further.
