### ISSUE TITLE
When I reset a Pomodoro, it will be counted in history and not a canceled Pomodoro.

### ISSUE THREAD

**Issue by rmoorenv** [schmich/marinara#273]
A Pomodoro is indivisible.

**Comment by schmich** [comment]
Unfortunately, I'm not able to reproduce this issue you're seeing.

No matter how I start/stop/restart Pomodoros, I cannot get it counted in history unless it expires and is fully completed.

Can you outline a specific set of steps to reproduce this behavior?

**Comment by rmoorenv** [comment]
You are right. Not sure why I thought it was counting it.

This is not an issue. User error? :)
