### ISSUE TITLE
Add support for long breaks

### ISSUE THREAD

**Issue by schmich** [schmich/marinara#28]
From Yasmin on Chrome Web Store review:
> Is there a way to alternate between short and long breaks? That would be awesome to have!

- Focus session
- Short break session (e.g. 5 mins)
- Long break session (e.g. 10-15 mins)
- Menu entries
- Configuration for alternating between short/long breaks (e.g. every-other, every 2nd, every 3rd, etc.)

**Comment by neffnet** [comment]
I'm also looking for the alternating short/long breaks feature. It would be nice to see how many short breaks you have left until your next long break.

Nice work so far, thank you!

**Comment by advaitju** [comment]
It would be good to have long breaks. Alternating could be an advanced feature. In my experience most Pomodoro timers use 3-short and 1-long break sequence, which is a good balance.
- Long break session (e.g. 10-15 mins)
- Configuration for alternating between short/long breaks (e.g. every-other, every 2nd, every 3rd, etc.)

**Comment by schmich** [comment]
I've added support for long breaks which will be present in the next update. There are a handful of bugs and smaller features left, but I'm hoping to publish an update in the next week or so.
