### ISSUE TITLE
Track Pomodoro completion history/stats

### ISSUE THREAD

**Issue by DukeDrummer** [schmich/marinara#29]
You can add a counter of how many pomodoros finished on a day.

**Comment by schmich** [comment]
Thanks for the suggestion. Just taking some notes here on the feature.

From Erica on the Chrome store:
> a history to see how many cycles you have done.

Features:
- Settings > History/Stats
- Browser action menu entry?
- Graph-style visualization over time
- Daily, weekly, monthly, cumulative stats
- Show summary stats on expiration page/desktop notification
- Might need `unlimitedStorage` permission to store data indefinitely
- Sync storage or just local storage (sync storage limits capacity)
- Ability to disable?
- Implementation: store timestamp on expiration, only store focus sessions, not break sessions

**Comment by schmich** [comment]
Early screenshot, work-in-progress:

![screen shot 2017-07-16 at 11 39 34 pm](https://user-images.githubusercontent.com/1562839/28255713-16a6b532-6a80-11e7-9165-7dad64a02b9b.png)

**Comment by schmich** [comment]
Implemented.
