### ISSUE TITLE
Marinara homepage redirecting to github

### ISSUE THREAD

**Issue by amyjepp27** [schmich/marinara#318]
When I right click on the timer and then click on the link for "Marinara: Pomodoro Assistant" (highlighted) it redirects to the main github page for this project: https://github.com/schmich/marinara. I really like the timer, but I totally get it if you're not supporting it anymore. You have contributed to a lot of productive hours for me in the last four years, so I appreciate it, even if I don't use it as consistently as I should. 

Thanks again! 
Amy 
![image](https://user-images.githubusercontent.com/64389647/80328180-6f294600-87f3-11ea-8bb7-bde783d766f1.png)

**Comment by mridulghanshala** [comment]
@amyjepp27  what do u expect it to do?

**Comment by schmich** [comment]
@amyjepp27 Thanks for the kind words!
