### ISSUE TITLE
marinara extension causing chrome to crash 

### ISSUE THREAD

**Issue by MPHstudent** [schmich/marinara#354]
I have removed all other chrome extensions except for marinara Pomodoro timer and it is causing chrome (on new MacBook air) to crash approximately every hour or so, sometimes more. Any advice on how to fix this or if anyone else is having this problem?

**Comment by schmich** [comment]
That is bizarre. I can't recall any other reports of Chrome crashing from this extension.

At absolute worst, if the extension crashed for some reason, Chrome should continue to function just fine. I believe each tab and extension runs in its own sandbox that shouldn't affect the rest of the browser. If anything, this sounds like a bug in Chrome.

- What version of Chrome are you using?
- I assume you installed the extension through the official Chrome Web Store?
- Does Chrome crash with the Marinara extension uninstalled?
- When it crashes, are you using the extension at all (active timer or on a break), or is it just installed?
- When it crashes, does it feel random, or does it seem to be triggered by something you're doing?

**Comment by schmich** [comment]
Closing without additional evidence.
