### ISSUE TITLE
Slight imperfection of the extension icon in Chrome

### ISSUE THREAD

**Issue by fabivs** [schmich/marinara#358]
Love the extension, thanks for the work and support, there is a slight detail that I just can't unsee now that I've noticed it.
The extension icon has a slim horizontal line on top of it which can be seen when the browser is in dark mode.

![icon1](https://user-images.githubusercontent.com/5720940/105074879-420b7a80-5a89-11eb-9a16-3ff9946ae315.png) ![icon2](https://user-images.githubusercontent.com/5720940/105074936-5b142b80-5a89-11eb-9b19-196891619eea.png)

**Comment by schmich** [comment]
Fixed. Will publish an update shortly. Thanks!
