### ISSUE TITLE
Option + s (on OS X) opens a dialogue box asking me to name my session

### ISSUE THREAD

**Issue by disastrid** [schmich/marinara#419]
Hi, 

After the last Chrome update I noticed that whenever I try to type the "ß" character in German using Option + s, Marinara opens a dialogue box asking me to name my session. 

I love Marinara but since I need to write every day in both English and German and I can't figure out how to turn this off (there's nothing about hot keys in the options), I might just have to uninstall, but I really don't want to!

Screenshots of dialogue and source attached (can't copy the text for some reason because of the code viewer, another great update feature from Chrome it seems)

<img width="820" alt="Screenshot 2022-02-04 at 15 21 12" src="https://user-images.githubusercontent.com/3051714/152545749-0ab5efb0-d772-4120-af8d-f58df50b7885.png">
<img width="686" alt="Screenshot 2022-02-04 at 15 25 59" src="https://user-images.githubusercontent.com/3051714/152545987-6e157f2c-0fed-4810-ba60-09980c781af8.png">

**Comment by schmich** [comment]
That screen is not from this extension. Marinara doesn't having any session naming. It must be another extension or program on your machine.

What's the URL in the source window? You might see a long string of random letters which would be the extension ID. For example, the Marinara options page lives at `chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/modules/options.html#/settings`.

Once you have the ID, you can see which extension it is, e.g. by visiting https://chrome.google.com/webstore/detail/lojgmehidjdhhbmpjfamhpkpodfcodef
