### ISSUE TITLE
Access history using python script

### ISSUE THREAD

**Issue by ameintjes** [schmich/marinara#434]
Is there a programmatic way to access the pomodoro history from outside Chrome?

I can imagine a scheduled python script to periodically extract and ingest this data into for example my own dashboard

**Comment by schmich** [comment]
Yes, this can be done with a little digging.

Marinara's extension data is stored using the [chrome.storage API](https://developer.chrome.com/docs/extensions/reference/storage/#property-local). This data is persisted on-disk by Chrome as a [LevelDB](https://www.dbdb.io/db/leveldb) database. All you have to do is determine where the extension data directory is, and then you can load that directory as a LevelDB instance using the library of your choice.

In my case, I'm running on Chrome on Windows with about 20 different user profiles. I have a development profile dedicated to Marinara. Marinara's Chrome extension ID is `lojgmehidjdhhbmpjfamhpkpodfcodef`, and on my machine the extension data is stored at `%LOCALAPPDATA%\Google\Chrome\User Data\Profile 8\Local Extension Settings\lojgmehidjdhhbmpjfamhpkpodfcodef`. In this case, `Profile 8` corresponds to my Chrome development user profile. These paths will be different on macOS of course, but the concept is the same.

This directory is a LevelDB data directory and can be loaded directly with a library. For example, here's a short JS snippet to dump Marinara's data using the [level Node library](https://github.com/level/level).

```js
const { Level } = require('level');
const path = require('path');

(async () => {
  const marinaraDataDir = path.join(process.env.LOCALAPPDATA, 'Google', 'Chrome', 'User Data', 'Profile 8', 'Local Extension Settings', 'lojgmehidjdhhbmpjfamhpkpodfcodef');
  const db = new Level(marinaraDataDir, { valueEncoding: 'json' });

  for await (const key of db.keys()) {
    let value = await db.get(key);
    console.log(key, value);
  }

  await db.close();
})();
```

On my dev profile with just a couple of completed pomodoros, I see the following output:

```
durations [ 2, 6 ]
pomodoros [ 27477682, 27477682 ]
timezones [ 2, 300 ]
version 1
```

This is the pomodoro data that Marinara stores. These are parallel RLE arrays (to save space). See [this comment](https://github.com/schmich/marinara/issues/47#issuecomment-354861670) for details on how to turn this into usable timestamps/durations.

**Comment by ameintjes** [comment]
Thank you for the detailed answer. It contained all the pointer info I was missing.

I now have a script working as planned *. 

* leveldb doesn't allow concurrent connections so it fails sometimes but that's not this plugin's fault
