### ISSUE TITLE
Contrast between red and black for dark mode systems

### ISSUE THREAD

**Issue by Sandwich1699975** [schmich/marinara#451]
The contrast for the pinned icon is difficult to see:

<img width="34" alt="Icon" src="https://user-images.githubusercontent.com/50229842/170905880-acc2040d-148b-4759-bfaa-bd01d680da9d.png">

---

MacOS 12.4 - MacBook Pro (14-inch, 2021)
Chrome - Version 102.0.5005.61 (Official Build) (arm64)
Dark mode enabled

**Comment by niteshmain** [comment]
I was just about to report the same issue. There should be an option to toggle the font color for the time remaining between a light and dark option.

**Comment by paulagual** [comment]
The same here, the contrast red/black make its very difficult to see the minutes remaining

MacBook Air (Retina, 13-inch, 2018)
Versión 102.0.5005.61 (Build oficial) (x86_64)
Dark mode enabled

**Comment by AgusCasarone** [comment]
I have the same issue, but with the green tomato. I use Edge in dark mode.

**Comment by Sandwich1699975** [comment]
Seems to be fixed now

<img width="36" alt="image" src="https://user-images.githubusercontent.com/50229842/178132368-f9f34bea-404d-426a-b443-d15e38f4d71f.png">

Version
34
