### ISSUE TITLE
Add import/export for Pomodoro history

### ISSUE THREAD

**Issue by schmich** [schmich/marinara#47]
- Since Pomodoro history is local only, we should support import/export
- JSON formatted
- Accessible from History page
- Should include `version` field to support back-compat importing

**Comment by mattecapu** [comment]
Hey, could you document the fomat you're using? It is a bit cryptic to decipher.

**Comment by schmich** [comment]
I will add a more detailed description to the wiki when I have more time, but for now:

- See [history.js](https://github.com/schmich/marinara/blob/master/src/background/history.js#L38) for an idea of working with history, and [rle.js](https://github.com/schmich/marinara/blob/master/src/background/rle.js) for basic RLE implementation
- History is stored so as to save space
- The history comprises three [parallel arrays](https://en.wikipedia.org/wiki/Parallel_array):
  - `pomodoros` is an array of [Unix timestamps](https://en.wikipedia.org/wiki/Unix_time) truncated to minute precision
  - `durations` is an [RLE-encoded](https://en.wikipedia.org/wiki/Run-length_encoding) array of Pomodoro durations in minutes (e.g. 25 minutes)
  - `timezones` is an RLE-encoded array of UTC hour offsets
- Once decoded, you can loop through all three arrays in parallel to determine when (to the minute) a Pomodoro was started in which timezone, and how long (in minutes) it lasted

I don't have any full decoding code since the stats and history are computed directly on the RLE-compressed arrays.

Let me know if you have more questions.

**Comment by jeznacki** [comment]
Is there an easy way to merge two history files (from two devices)?
