### ISSUE TITLE
Add ability to start a new pomodoro cycle from the main menu

### ISSUE THREAD

**Issue by melissaintrees** [schmich/marinara#50]
Now can you right click at top tomato and click start long break & start focusing in succession and it will reset the pom cycle? I'm testing that to see if it works...Maybe please add a "Start Pomadoro Cycle," to the extension bar tomato and it will reset the cycle of 4 short breaks one long break. Thanks! And thanks for adding that cycle option!

**Comment by melissaintrees** [comment]
Hey it works to reset the pomodoro cycle to right click start long break & start focusing in succession from the extension bar. Might make it easier to add the "Start Pomadoro Cycle" option there though...Thank You!

**Comment by melissaintrees** [comment]
Now I see stop timer option when the timer is on and am assuming that works to reset the cycle. So nevermind. 👍

**Comment by schmich** [comment]
Your findings are correct. Currently, the only way to reset a cycle is to start a long break first and then start focusing/short break.

Resetting the cycle is definitely needed. People probably don't want to carry over their cycle from the previous day, so they need a way to start a new cycle.

I like your suggestion of adding "Start Pomodoro Cycle" to the menu. It will reset the cycle and start the focus session timer (the first pomodoro).

I will work on getting this fixed. Thanks for the feedback.

**Comment by melissaintrees** [comment]
Awesome...I will employ that technique and look forward to seeing how the changes are updated in the code. 

I'm glad to help out with an extension that has been so helpful to me!

**Comment by schmich** [comment]
I'm not sure that people will intuitively understand what "Start Pomodoro Cycle" means, so I'm open to other suggestions.

This change will be in the next big 2.1.0 update which should be out in the next week or so.

![screen shot 2017-07-16 at 11 06 23 pm](https://user-images.githubusercontent.com/1562839/28255356-6d32e718-6a7b-11e7-8b25-903ed841f4d7.png)

**Comment by melissaintrees** [comment]
Maybe "reset cycle" or "start new cycle" in the start timer menu?
