### ISSUE TITLE
Extension error on Egde "This extension contains malware."

### ISSUE THREAD

**Issue by ngoctt18** [schmich/marinara#514]
Marinara: Pomodoro® Assistant show error "This extension contains malware." on Edge browser like this. Please check it out!
Extension Version 34.

![image](https://github.com/schmich/marinara/assets/33822205/e976e281-a0a9-4f58-b76a-62dde3ffe417)
![image](https://github.com/schmich/marinara/assets/33822205/ba3e24ad-f117-4e2f-883b-9b4936afa0d7)

**Comment by schmich** [comment]
I have only published this extension to the [Chrome Web Store](https://chrome.google.com/webstore/detail/marinara/lojgmehidjdhhbmpjfamhpkpodfcodef).

I have not published this for any other browser besides Chrome. Can you provide a link to the extension listing for Edge? I searched various terms on the [Edge Add-ons page](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home) and I'm not able to find the extension listed anywhere.

It's possible that someone squatted the name and published something malicious. Who does it show as the author?

**Comment by ngoctt18** [comment]
Chrome extensions can be installed on Edge. I uninstalled the extension and reinstalled it and no more errors.
This is Extension [link ](https://chromewebstore.google.com/detail/marinara-tr%E1%BB%A3-l%C3%BD-pomodoro%C2%AE/lojgmehidjdhhbmpjfamhpkpodfcodef)

Thanks!
