### ISSUE TITLE
Feature: Add comments/tasks completed when pomodoro ends

### ISSUE THREAD

**Issue by xmtrinidad** [schmich/marinara#70]
Just want to say I've been using this pomodoro exclusively to stay productive.  One thing I'm doing separately in a document is keeping track of what I did during a pomodoro after it's completed.  I think it would be a great feature to add so that users can review what they accomplished during their previous sessions.

**Comment by schmich** [comment]
Thanks for the feedback. What you're describing sounds like the featured discussed in #56.

If that's the case, I'd like to take your feedback here, add it to #56, and close this issue as a duplicate of that one so we don't have two issues tracking the same feature.

**Comment by schmich** [comment]
I added your comment to #56. I'm closing this and tracking the feature there. Thanks again for your input.

**Comment by xmtrinidad** [comment]
Sounds good, it was just a feature suggestion.  As I said, I use this pomodoro exclusively so thanks for what you do.
