### ISSUE TITLE
Add volume control for the alarms

### ISSUE THREAD

**Issue by DavidFerland7** [schmich/marinara#71]
Hi,
great extension, love the feature.

Please add a volume control, the alarms are so loud at standard volume.
Thanks

**Comment by schmich** [comment]
Thanks for the feedback.

The alarms do seem loud, but I'd rather avoid adding volume controls. They add complexity to the extension (more settings, and with volume controls would probably come a "Test" button to see how loud the alarm is), and I'm fighting against that as much as possible.

I might just try re-leveling the alarm sounds at a lower volume. If that doesn't work well, perhaps a volume control is needed.

**Comment by DavidFerland7** [comment]
Totally agree.
Thanks for your quick answer, let me know if you adjust down the volume.
David

**Comment by schmich** [comment]
Which alarm in particular seemed loud?

**Comment by Cyber1000** [comment]
Funny, to me the alarm seems too quiet :-)
Especially, when listening to music on my laptop.
So it may depend, is there another setting (in chrome?) to set the volume?

**Comment by schmich** [comment]
@Cyber1000 Which alarm are you using that seemed too quiet?

To my knowledge, Chrome has no global volume control. I am using a handful of Creative Commons licensed sounds, and their volume levels were never normalized, so they sound very different. It's possible that normalizing will make the quieter alarms louder.

**Comment by Cyber1000** [comment]
"Battle Horn" seemed too quiet, when listening to music. "Bike Horn" seems to be ok, so I think I'll stick to this for now.

Yes, seems that the sounds are quite different in their loudness.

**Comment by schmich** [comment]
c1917a95c495e8a2fc20a68ec62ea57ec6e6ab2b should fix this. Volumes and perceived loudness were matched across all audio files. I'm not an audio engineer, and the results weren't perfect, but I think it's reasonable.

These changes will be present in the next release.
