### ISSUE TITLE
Publish extension for Firefox

### ISSUE THREAD

**Issue by schmich** [schmich/marinara#81]
- See PR #80
- Need to do more testing: settings (sync), sounds, notifications
- Register with FF
- Update build scripts
- Publish extension
- Update README to include FF support
- Get valid extension ID:
  - See `manifest.json`
  - https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications
  - https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#id
  - https://developer.mozilla.org/en-US/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID

**Comment by MarkBennett** [comment]
This is great! I'm actively running it and trying to get it working right now. As I find issues do you want me to file them against the repo, or just create a PR and work against that? I know for sure that the notifications have trouble right now as the buttons option isn't supported on `chrome.notifications.create()` or `update()`.

**Comment by schmich** [comment]
I always welcome pull requests. If the existing code isn't too messy to understand and the changes aren't too burdensome, feel free to create a PR.

If something is too complex or you think it would take you forever to get up-to-speed just to change something, you can file an issue and I'll take a look at it.

No button support is a bummer, but Chrome on macOS uses the macOS-style notifications now, so the buttons are hidden behind a dropdown menu, anyway.

**Comment by MarkBennett** [comment]
Sounds good! Thanks @schmich!

**Comment by schmich** [comment]
I had to remove the `applications` property from `manifest.json` since I was getting warnings in Chrome (see #88) and I'm planning on publishing an update soon.

To support both Chrome and Firefox, I think we'll need to dynamically generate `manifest.json` for Firefox. I filed #106 to track this.

**Comment by schmich** [comment]
Closing this non-specific issue in favor of the more specific Firefox issues created. See the [Firefox milestone](https://github.com/schmich/marinara/milestone/8) for more details.
