### ISSUE TITLE
Add support for long breaks

### ISSUE THREAD

**Issue by schmich** [schmich/marinara#9]
- Context menu entry
- Options page setting
- Default 15 minutes?

**Comment by tainarareis** [comment]
Hi @schmich. I want to lear javascript. Which source do you recommend me to use for learning? Thank you.

**Comment by schmich** [comment]
Hi @tainarareis, I'm happy to help, but this issue is not the right place to do it. I see your email on your profile, so I'll send you some information there.

**Comment by schmich** [comment]
Duplicate of the more specific #28. Closing.
